### PR TITLE
Build AWS Lambda layers for canvas 2.8.0

### PR DESCRIPTION
**Pull request by maxpeterson**
For #14 

Update the Dockerfile to build the latest canvas version (2.8.0).

To get the canvas layers to work on lambda I updated the  Dockerfile to use the `lambci/lambda:build-nodejsXYZ.x` image and run `npm install` with the `--build-from-source ` flag.

Other changes included:

* Using `lddtree.sh` to find the `so` library dependencies (inspired by [node-canvas/prebuild/Linux/bundle.sh#L1](https://github.com/Automattic/node-canvas/blob/0d9ca8861cb1c30793f7d8526b0ccb0e035d0906/prebuild/Linux/bundle.sh#L1))
* Using `docker cp` to copy the layer zip files out of the docker image.
* Using `docker-compose.yml` and a  `Makefile` to help setup, test and debug running canvas locally using the lambda image, as well as to simplify the build process. 

@jwerre some of changes here were the result of my testing / development process (such as using make and docker-compose). Let me know if you would like me to strip them out or make any other changes.

### CODE REVIEW

**Comment by maxpeterson** [comment]
Just to confirm, do you wan't me to remove the `docker-compose.yml`, `build.sh` and the `test` stuff?

**Comment by jwerre** [comment]
> Just to confirm, do you wan't me to remove the `docker-compose.yml`, `build.sh` and the `test` stuff?
Yes, please

**Comment by jwerre** [comment]
On second thought why don't you just leave it there and document it in the readme so everyone is clear about what it does.

**Comment by maxpeterson** [comment]
@jwerre I have updated this PR. Let me know what you think.

One further thing that occurred to me is that the two zip files now seem to be much smaller than before, so they could be combined into into a single zip file that would be around 8.5M

**Comment by jwerre** [comment]
@maxpeterson, I finally got around to merging this. Sorry for letting your work slip through the cracks. It should be up and running now so let me know if you comments or improvements.

**Pull request merged**
